#
# Makefile for RKSUITE
#
#----------------------------------------
# LIB  =  librksuite_cg92.a
#----------------------------------------
$(LIB): $(LIB_OBJ)
	( \
         ar ruv $(LIB) $? ;\
         $(RANLIB) $(LIB) ;\
)
